[theme]
theme = "dracula"

[icons]
icons = "awesome6"

[[block]]
block = "music"
player = "spotify"
# [[block.click]]
# button = "left"
#  = ["prev", "play_pause", "next"]

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_used_percents.eng(w:1) "
interval = 10
warning_mem = 75
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) "
interval = 1

[[block]]
block = "bluetooth"
mac = "48:5A:B6:EF:33:47"
disconnected_format = ""

[[block]]
block = "backlight"
device = "intel_backlight"
minimum = 1
maximum = 100
step_width = 1
cycle = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%a %d/%m %T', l:fr_FR) "

[[block]]
block = "battery"
format = " $icon $percentage "
